---
- include: install-erlang.yml 
- include: install-rebar.yml

- name: append to the $PATH
  hosts: guests
  tasks:
    - name: add erlang and rebar to path 
      tags: add_erl_rebar_path
      template: src=templates/bashrc dest=~/.bashrc mode=666 backup=yes
